name: App Request
about: Infos about the app
title: ''
labels: 'app request'
assignees: kurtschambach
body:
- type: input
  attributes:
    label: Name
    description: Name of the App you want to request
- type: textarea
  attributes:
    label: Description
    description: A short description of the App.
  validations:
    required: true
- type: input
  attributes:
    label: Link
    description: Please add a link, so we can find the app quick
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about your request here.
  validations:
    required: false
